name: Publish docs via GitHub
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install mkdocs-jupyter and mkdocstrings
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material mkdocs-jupyter mkdocstrings

      - uses: actions/cache@v3
        id: cached-python-env
        with:
          path: ${{ env.pythonLocation }}
          key: >
            python
            ${{ runner.os }}
            python-3.9
            ${{ hashFiles('requirements.txt') }}
      - name: Install dependencies
        if: steps.cached-python-env.outputs.cache-hit != 'true'
        run: |
          pip install -r requirements.txt
      - name: remove requirements file
        run: rm -Rf requirements.txt
      - name: Check install packages
        run: pip freeze
        -name: Build docs
        run: mkdocs build --clean
      - name: Deploy docs
        uses: peaceiris/action-gh-pages@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
