name: Publish docs via GitHub
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: update pip
        run: python -m pip install --upgrade pip
      - name: run requirements
        run: pip install -r requirements.txt
      - name: remove requirements file
        run: rm -Rf requirements.txt
      - name: Check install packages
        run: pip freeze
      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@1.16
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
